### ISSUE TITLE
 请教  consult

### ISSUE THREAD

**Issue by JYiCao** [tkcoding/reinforcement_learning#1]
hello,I found a file about 'log_data_per_day.csv' missing when I was studying your project,I look forward to your help.Thanks

**Comment by tkcoding** [comment]
Hi , I have added a sample_file.csv for a new version. However it's only short version of what field it suppose to consists of . For different constraint you might want to modify the file and add the field yourself. 

I cant share you the full file due to confidentiality.  you can add your entry into the file in sample_file.csv for different machine so that it will be taken into account during Q-learning session.

**Comment by tkcoding** [comment]
Hi you can refer to my latest commit . I have made reconstruct the .csv as it just needed to simulate actual time step that product being release in real production environment. 

https://github.com/tkcoding/reinforcement_learning/commit/86a02394b3c161d119b7a067897eeab45abd6e76

**Comment by JYiCao** [comment]
I'm really happy to receive your reply. It never occurred to me that you not only replied to my letter, but also submitted data information. I cannot express my gratitude to you. You are really a kind friend.I wish you a smooth job and a happy life. If you have the opportunity, welcome to China.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tkcoding/reinforcement_learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tkcoding/reinforcement_learning]  请教  consult (Issue #1)





 
Hi you can refer to my latest commit . I have made reconstruct the .csv as it just needed to simulate actual time step that product being release in real production environment.
 
86a0239
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tkcoding** [comment]
Thank you Cao , you are welcome. Thanks for filing the issue so that I am aware of the file is missing as well. All the best to you too.

**Comment by JYiCao** [comment]
you are welcome
